---
version: "3.3"
services:
    jenkins:
        build:
            context: ./jenkins
            args:
                dockergid: ${_CI_DOCKER_GID}  # Host docker gid
        restart: unless-stopped
        environment:
            - TZ=${TIMEZONE}
        volumes:
            - /var/jenkins_home:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
            - /tmp:/tmp
            - .:/opt/docker
            - ${NFS_DIR}:/var/jenkins_home/nfs
            - ${TFTP_DIR}:/var/jenkins_home/tftp
            - "/etc/localtime:/etc/localtime:ro"
        ports:
            - 8080:8080
            - 50000:50000
        devices:
            - "/dev/net/tun:/dev/net/tun"
        network_mode: "host"
    tftp:
        build:
            context: ./tftp
        volumes:
            - ${TFTP_DIR}:/srv/tftp
        ports:
            - 69:69/udp
    nfs:
        image: itsthenetwork/nfs-server-alpine:12
        container_name: nfs
        restart: unless-stopped
        privileged: true
        environment:
            - SHARED_DIRECTORY=/srv/nfs
        volumes:
            - ${NFS_DIR}:/srv/nfs
        ports:
            - 2049:2049
